# Generated by Django 2.2.4 on 2019-08-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('Aa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Aa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('Aa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time_spent', models.TimeField(default=None)),
                ('dec_name', models.CharField(default=None, max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Clientele')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
        ),
    ]
