# Generated by Django 2.2.4 on 2019-09-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('Aa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Aa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('Aa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mother_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('Aa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time_spent', models.CharField(choices=[('5', '5 λεπτά'), ('10', '10 λεπτά'), ('15', '15 λεπτά'), ('20', '20 λεπτά'), ('30', '30 λεπτά'), ('45', '45 λεπτά'), ('60', '1 ώρα'), ('90', '1:30 ώρες'), ('120', '2:00 ώρες'), ('150', '2:30 ώρες'), ('180', '3:00 ώρες'), ('210', '3:30 ώρες'), ('240', '4:00 ώρες')], max_length=20)),
                ('dec_name', models.CharField(default=None, max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Clientele')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
                ('sub_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubTask')),
            ],
        ),
    ]
