# Generated by Django 2.2.4 on 2019-08-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190828_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='Aa',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
