# Generated by Django 2.2.4 on 2019-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190828_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='time_spent',
            field=models.CharField(choices=[('5', '5 λεπτά'), ('10', '10 λεπτά'), ('15', '15 λεπτά'), ('20', '20 λεπτά'), ('30', '30 λεπτά'), ('45', '45 λεπτά'), ('60', '1 ώρα'), ('90', '1:30 ώρες'), ('120', '2:00 ώρες'), ('150', '2:30 ώρες'), ('180', '3:00 ώρες'), ('210', '3:30 ώρες'), ('240', '4:00 ώρες')], max_length=20),
        ),
    ]
