# Generated by Django 2.2.4 on 2019-09-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190902_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('number', models.PositiveIntegerField(choices=[('A', ((1, '1'), (2, '2'), (3, '3'))), ('B', ((4, '4'), (5, '5'), (6, '6')))])),
            ],
        ),
    ]
