# Generated by Django 2.2.5 on 2019-09-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_example'),
    ]

    # 0005_auto_20190904_1022 also deletes Example. A second DeleteModel
    # fails on a new database, so this historical migration is a no-op.
    operations = [
    ]
