# Generated by Django 2.2.4 on 2019-09-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='subtask',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='GroupName'), on_delete=django.db.models.deletion.CASCADE, to='core.SubTask'),
        ),
    ]
