# Generated by Django 2.2.5 on 2019-09-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
