# Generated by Django 2.2.4 on 2019-09-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190904_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubTask'),
        ),
    ]
